abstract final class RouteNames {
  static const home = 'home';
  static const login = 'login';
  static const signUp = 'signUp';
  static const checklists = 'checklists';
  static const checklistCreate = 'checklistCreate';
  static const checklistEdit = 'checklistEdit';
  static const checklistDetail = 'checklistDetail';
  static const checklistWizard = 'checklistWizard';
  static const attendance = 'attendance';
  static const teamEvents = 'teamEvents';
  static const teamDetail = 'teamDetail';
  static const eventDetail = 'eventDetail';
  static const joinTeam = 'joinTeam';
  static const profile = 'profile';
  static const clubs = 'clubs';
  static const clubDetail = 'clubDetail';
  static const news = 'news';
  static const newsCreate = 'newsCreate';
  static const finance = 'finance';
  static const contributionCreate = 'contributionCreate';
  static const standings = 'standings';
}
